# Generated by Django 5.2.10 on 2026-02-06 19:09

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_taskgoal_timegoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timegoal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timegoal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timegoal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='timegoal',
            unique_together={('user', 'period', 'date')},
        ),
    ]
